import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import personalLogo from '../assets/ANlogoWhiteTransparent.png'
import Image from "next/image";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="bg-black w-full px-20">
        <Image
          src={personalLogo}
          alt="brand"
          width={80}
          height={80}
          />
        </div>
        <main className="min-h-screen">{children}</main>

        <footer className="bg-black w-full flex  flex-row-reverse justify-center items-center text-white font-semibold">
          <h3>Mady by A.N.PRONOY </h3>
          <Image
          src={personalLogo}
          alt="brand"
          width={40}
          height={40}
          />
        </footer>
      </body>
    </html>
  );
}
